### ISSUE TITLE
Seeing “The process '/usr/bin/gpg' failed with exit code 2“

### ISSUE THREAD

**Issue by cbaker6** [sersoft-gmbh/swifty-linux-action#187]
Starting to see this failure every few builds https://github.com/netreconlab/Parse-Swift/actions/runs/8215076688/job/22468187253?pr=157#step:3:122

Rerunning passes after a couple of times.

My action looks like: https://github.com/netreconlab/Parse-Swift/blob/87742c976be2242cc95e0aa06213561b1ae00ab8/.github/workflows/ci.yml#L113

**Comment by ffried** [comment]
Can you please re-run the action with debug logs enabled?

As a temporary workaround you can also use `skip-gpg-check: true` to skip she gpg check.

**Comment by cbaker6** [comment]
Closing for now, I haven’t seen the issue show up again the last few times I committed
